"""
operators/gen_3d_object/operator.py

Gen3DObjectOperator — accepts a loaded model and processes an input dict into a
3D output (GLB file on disk).

The operator is intentionally model-agnostic: you inject any object that
implements the same interface as `TripoModel`.  New model wrappers can be
swapped in without touching this file.

Output layout — two modes, chosen by whether `output_dir` is given:

  * **per-game (default, `output_dir=None`)** — resolved by
    `pipeline.common.paths`, so artifacts are grouped by generated game project::

        test_data/outputs/<game_id>/<run_id>/assets/3d_object/<task_id>/
            ├── model.glb
            └── meta.json

  * **flat (legacy, `output_dir="..."`)** — writes `<output_dir>/<task_id>.glb`,
    byte-for-byte the historical behaviour. Existing callers are unaffected.

Usage:
    from models.gen_3d_object.tripo_model import TripoModel
    from operators.gen_3d_object.operator import Gen3DObjectOperator

    model = TripoModel(model_path="v3.1-20260211")

    # per-game layout
    op = Gen3DObjectOperator(model=model, run_id="20260731_1032")

    # legacy flat layout (unchanged)
    op = Gen3DObjectOperator(model=model, output_dir="outputs/3d_object")

    result = op.run({
        "game_id": "gameA_cyberpunk_shooter",   # optional, inferred when omitted
        "task_id": "sword_001",
        "image_path": "path/to/image.png",      # or "image": PIL.Image
        "seed": 42,
    })
    print(result["glb_path"])

One optional extra, additive and off unless asked for:

  * ``run_art_plan(game_id, image_model)`` generates a whole game's
    recorded art plan (``funcs/art_plan.py``) in one call.

A second route skips inference entirely. Passing ``spec`` instead of an
image builds the mesh from a declarative part list
(``funcs/code_asset.py``), which suits anything exactly describable — a
crate, a sign, a wheel, a rifle. It needs no model and no GPU, states its
own facing and size instead of leaving them to be guessed, and keeps its
parts as named glTF nodes so gameplay can still move them::

    op = Gen3DObjectOperator(model=None, run_id="20260826_1400")
    op.run({
        "game_id": "gameA_cyberpunk_shooter",
        "task_id": "crate_001",
        "spec": {
            "subject": "wooden supply crate",
            "units": "metres", "forward": "+z",
            "asset_type": "prop", "height_metres": 0.6,
            "parts": [{"id": "body", "kind": "box",
                       "size": [0.6, 0.6, 0.6], "at": [0, 0.3, 0]}],
        },
    })

The two can be mixed, which is usually the best available answer for a
detailed hard-surface asset. A ``mesh`` part reads a GLB off disk — one
component generated by a cloud model — and is placed, measured and gated
exactly like a primitive. What each side contributes is not
interchangeable: the generator supplies shapes no formula states (a
moulded grip's finger swells), and the spec supplies the dimensions and
placement a prompt cannot specify (a rail's 30 mm slot pitch). Spending
generation on something a lathe states exactly buys an approximation at a
hundred times the triangles, and the approximation is the part that can no
longer be adjusted by editing a number — so the ``provenance`` gate
reports what was delegated and at what cost::

    op.run({
        "game_id": "gameA_cyberpunk_shooter",
        "task_id": "rifle_001",
        "spec": {
            "subject": "assault rifle",
            "units": "metres", "forward": "+z",
            "asset_type": "weapon", "height_metres": 0.24,
            "parts": [
                # exact dimensions: stated
                {"id": "receiver", "kind": "box",
                 "size": [0.04, 0.048, 0.30], "at": [0, 0.139, -0.03]},
                # moulded surface: fetched, with a uniform `size` so the
                # mesh keeps the proportions it was generated with
                {"id": "grip", "kind": "mesh",
                 "source": "parts/grip.glb",
                 "size": [0.116, 0.116, 0.116], "at": [0, 0.045, -0.104]},
            ],
        },
    })
"""

import time
from pathlib import Path
from typing import Any, Optional

from PIL import Image

#: Registered task kind for this operator (see pipeline/common/paths.py).
TASK_KIND = "3d_object"

#: Artifact filename used by the per-game layout.
GLB_FILENAME = "model.glb"


class Gen3DObjectOperator:
    """
    Operator for 3D object generation.

    Args:
        model: A loaded model with an `infer_and_save(image, output_path, ...)` method.
               Currently supports TripoModel and MeshyModel; any model with the
               same interface works.
        output_dir (str, optional): **Legacy flat mode.** When given, every GLB is
               written as `<output_dir>/<task_id>.glb`, exactly as before. When
               omitted (default), the per-game layout under
               `test_data/outputs/<game_id>/<run_id>/assets/3d_object/<task_id>/`
               is used instead.
        run_id (str): Groups all artifacts of one generation run. Per-game mode only.
        default_game_id (str, optional): Fallback game project for tasks that carry
               no `game_id` and whose input paths reveal none. Per-game mode only.
    """

    def __init__(
        self,
        model: Any,
        output_dir: Optional[str] = None,
        run_id: str = "default",
        default_game_id: Optional[str] = None,
    ):
        self.model = model
        self.run_id = run_id
        self.default_game_id = default_game_id
        # Legacy flat mode is active only when an explicit output_dir is supplied.
        self.output_dir = Path(output_dir) if output_dir else None
        if self.output_dir is not None:
            self.output_dir.mkdir(parents=True, exist_ok=True)

    # --------------------------------------------------------------------------

    def _load_image(self, inp: dict) -> Image.Image:
        """Return a PIL image from an input dict that has 'image_path' or 'image'."""
        if "image" in inp and isinstance(inp["image"], Image.Image):
            return inp["image"]
        if "image_path" in inp:
            p = Path(inp["image_path"])
            if not p.is_absolute() and not p.exists():
                # resolve relative to repo root (codes_official/)
                repo_root = Path(__file__).resolve().parents[2]
                p = repo_root / inp["image_path"]
            return Image.open(str(p)).convert("RGBA")
        raise ValueError("Input must contain 'image_path' (str) or 'image' (PIL.Image).")

    # --------------------------------------------------------------------------

    def _artifact_suffix(self) -> str:
        """
        File extension for the artifact — GLB unless the injected model says
        otherwise (the cloud backends can emit FBX / OBJ / USDZ).

        The result dict keeps the ``glb_path`` key whatever the extension is:
        renaming a returned key breaks `eval.py` and `test/`.
        """
        fmt = getattr(self.model, "output_format", None)
        return str(fmt).lower().lstrip(".") if fmt else "glb"

    def _resolve_out_path(self, inp: dict, task_id: str) -> tuple[str, Path, Path]:
        """
        Return ``(game_id, task_dir, glb_path)`` for either output mode.

        Legacy flat mode keeps the historical `<output_dir>/<task_id>.glb`.
        """
        suffix = self._artifact_suffix()
        if self.output_dir is not None:
            game_id = str(inp.get("game_id") or inp.get("game") or "")
            return game_id, self.output_dir, self.output_dir / f"{task_id}.{suffix}"

        from pipeline.common import paths
        game_id = paths.infer_game_id(inp, fallback=self.default_game_id)
        task_dir = paths.task_output_dir(game_id, TASK_KIND, task_id, run_id=self.run_id)
        filename = GLB_FILENAME if suffix == "glb" else f"model.{suffix}"
        return game_id, task_dir, task_dir / filename

    # --------------------------------------------------------------------------

    def run(self, inp: dict) -> dict:
        """
        Generate a 3D object from an image prompt, or build one from a spec.

        Args:
            inp (dict):
                - image_path (str): path to the reference / concept image
                  OR image (PIL.Image): pre-loaded image
                  OR spec (dict): a part spec, which builds the mesh instead
                  of inferring it (see `funcs/code_asset.py`)
                - compose (dict): combine_avatar arguments, including caller-defined
                  socket_definitions, grip_templates and optional slot_definitions
                - game_id (str, optional): game project this task belongs to;
                  inferred from `image_path` when omitted
                - task_id (str, optional): used to name the output file / directory
                - seed (int, optional): random seed (default 42)
                - decimation_target (int, optional)
                - texture_size (int, optional)

        Returns:
            dict:
                - task_id (str)
                - glb_path (str): absolute path to the saved GLB file
                - elapsed_sec (float)
                - game_id (str), task_kind (str), output_dir (str)  ← additive
        """
        if inp.get("compose") is not None:
            if inp.get("spec") is not None:
                raise ValueError("provide compose or spec, not both")
            return self._run_compose(inp)
        if inp.get("spec") is not None:
            return self._run_spec(inp)

        task_id = inp.get("task_id", f"task_{int(time.time())}")
        seed = inp.get("seed", 42)
        decimation_target = inp.get("decimation_target", 1_000_000)
        texture_size = inp.get("texture_size", 4096)

        game_id, task_dir, out_path = self._resolve_out_path(inp, task_id)

        image = self._load_image(inp)

        t0 = time.time()
        glb_path = self.model.infer_and_save(
            image,
            output_path=str(out_path),
            seed=seed,
            decimation_target=decimation_target,
            texture_size=texture_size,
        )
        elapsed = time.time() - t0

        result = {
            "task_id": task_id,
            "glb_path": glb_path,
            "elapsed_sec": round(elapsed, 2),
            "game_id": game_id,
            "task_kind": TASK_KIND,
            "output_dir": str(task_dir),
        }

        # Image-to-3D infers a floor under a subject that stands on the edge
        # of its own crop, and it is never wanted: measured at a fifth of the
        # triangle budget, and a grey pancake under the character in the
        # scene. Removing it here means every consumer of this task output
        # gets a clean mesh, rather than each game discovering the slab.
        if inp.get("strip_ground_plate", True):
            from .funcs.mesh_cleanup import strip_ground_plate

            cleanup = strip_ground_plate(glb_path)
            result["ground_plate"] = cleanup
            if cleanup.get("applied"):
                result.setdefault("warnings", []).append(
                    f"removed an inferred floor: {cleanup['plate_count']} "
                    f"sheets and {cleanup['debris_count']} loose lumps, "
                    f"{cleanup['removed_fraction']:.0%} of the mesh"
                )
            elif cleanup.get("reason") and "nothing" not in cleanup["reason"]:
                result.setdefault("warnings", []).append(
                    f"left the mesh alone: {cleanup['reason']}"
                )

        # meta.json only in per-game mode, so legacy output dirs stay untouched.
        if self.output_dir is None:
            from pipeline.common import paths
            meta = {
                **result,
                "run_id": self.run_id,
                "prompt": inp.get("prompt"),
                "source_image": inp.get("image_path"),
                "seed": seed,
                "decimation_target": decimation_target,
                "texture_size": texture_size,
                "model": type(self.model).__name__,
            }
            for key in ("asset_id", "asset_type", "forward_axis",
                        "scale_hint_metres", "notes"):
                if inp.get(key) is not None:
                    meta[key] = inp[key]
            # Cloud backends expose what the call cost and produced — task id,
            # credits, triangle count (api_model_require.md R9.8). Recording it
            # here is what makes a billed run reproducible after the fact.
            call_info = getattr(self.model, "last_call_info", None)
            if call_info:
                meta["model_call"] = dict(call_info)
            paths.write_task_meta(task_dir, meta)

        return result

    # --------------------------------------------------------------------------

    def _run_compose(self, inp: dict) -> dict:
        """Resolve caller-configured attachments, then build through the spec route."""
        import json
        from .funcs.code_asset_templates.human_template.combine import (
            combine_avatar, write_report,
        )

        task_id = inp.get("task_id", f"task_{int(time.time())}")
        _, _, out_path = self._resolve_out_path(inp, task_id)
        directory = out_path.parent / f"{out_path.stem}_compose"
        config = dict(inp["compose"])
        config.setdefault("parts_dir", directory / "parts")
        started = time.time()
        combined = combine_avatar(**config)
        result = self._run_spec({**inp, "task_id": task_id, "spec": combined["spec"]})
        report_path = write_report(combined["report"], directory / "report.json")
        sockets_path = directory / "sockets.json"
        sockets_path.write_text(json.dumps(combined["report"]["sockets"], indent=2),
                                encoding="utf-8")
        result["compose"] = {**combined["report"], "report_path": report_path,
                             "sockets_path": str(sockets_path)}
        result["elapsed_sec"] = round(time.time() - started, 2)
        return result

    def _run_spec(self, inp: dict) -> dict:
        """Build the asset from a declarative spec rather than an image.

        Taken when the task carries a ``spec``. No model is loaded and no
        image is read, so this path works with ``model=None`` — a crate
        does not need a GPU, and requiring one to build a box is what makes
        primitives feel like a defeat rather than a choice.

        Three things come out of the spec that the generated path can only
        guess at, which is the reason to prefer it wherever it applies:

          * ``forward_axis`` is *stated* in the task output, so a consumer
            can read the facing off the record instead of inferring it from
            a view. Facing is the one property `orientation_review` exists
            to establish, and here there is nothing to establish.
          * ``scale_hint_metres`` is stated, so the mesh has a real size
            instead of a unit box someone has to scale by eye.
          * parts keep their ids as glTF node names, so a wheel can be spun
            after import. A reconstructed mesh is one fused body.

        ``strip_ground_plate`` is deliberately not run: it removes a floor
        that image-to-3D *invented*, and a spec cannot invent one. Running
        it here would risk deleting a plinth that was asked for.

        A spec may also carry ``mesh`` parts, which read a GLB off disk —
        typically one component from a cloud model, composed in where no
        formula states the shape. Those change one thing here and nothing
        else: the result reports them under ``generated_parts``, because a
        fetched part's facing was *asserted* by whoever placed it and not
        established by anything. A reviewer needs to know that editing the
        placement does not change the geometry underneath it.
        """
        from .funcs.code_asset import MESH_KIND, build_code_asset

        task_id = inp.get("task_id", f"task_{int(time.time())}")
        game_id, task_dir, out_path = self._resolve_out_path(inp, task_id)
        # A spec always yields glTF, whatever output_format an injected
        # model happens to advertise.
        out_path = out_path.with_suffix(".glb")
        task_dir.mkdir(parents=True, exist_ok=True)

        t0 = time.time()
        report = build_code_asset(
            inp["spec"],
            str(out_path),
            revise=inp.get("revise"),
            strict=bool(inp.get("strict", True)),
        )
        elapsed = time.time() - t0

        # Which parts were fetched rather than derived. Carried on the result
        # because after export the two are indistinguishable, and only one of
        # them can still be changed by editing a number: a reviewer who wants
        # the grip 4 mm thicker needs to know that means regenerating it.
        # `long_axis` travels too, since a regenerated part is a new set of
        # axes and the rotation that placed the old one will not place it.
        generated_parts = [
            {
                "id": part["id"],
                "source": part["source"],
                "long_axis": part.get("long_axis"),
            }
            for part in report["spec"]["parts"]
            if part.get("kind") == MESH_KIND
        ]

        result: dict[str, Any] = {
            "task_id": task_id,
            "glb_path": report["glb_path"],
            "elapsed_sec": round(elapsed, 2),
            "game_id": game_id,
            "task_kind": TASK_KIND,
            "output_dir": str(task_dir),
            "source": "code_asset+generated" if generated_parts else "code_asset",
            "spec_ok": report["ok"],
            "gates": report["gates"],
            "triangles": report["triangles"],
            "bounds": report["bounds"],
            "part_ids": report["part_ids"],
            "generated_parts": generated_parts,
            "stop_reason": report["stop_reason"],
            "attempts": report["attempts"],
        }
        if report["warnings"]:
            result.setdefault("warnings", []).extend(report["warnings"])
        if report["failures"]:
            # Surfaced as warnings on the result *and* kept in `gates`: a
            # gate failure that only appears in a nested dict is the silent
            # early return this whole module is shaped against.
            result.setdefault("warnings", []).extend(
                f"gate: {message}" for message in report["failures"]
            )

        if self.output_dir is None:
            from pipeline.common import paths

            meta = {
                **result,
                "run_id": self.run_id,
                "spec": report["spec"],
                "forward_axis": report["forward_axis"],
                "scale_hint_metres": report["scale_hint_metres"],
                "model": "code_asset",
            }
            for key in ("asset_id", "asset_type", "notes"):
                if inp.get(key) is not None:
                    meta[key] = inp[key]
            paths.write_task_meta(task_dir, meta)

        return result

    # --------------------------------------------------------------------------

    def run_art_plan(
        self,
        game_id: str,
        image_model: Any = None,
        plan: Optional[list[dict]] = None,
        assets: tuple[str, ...] = (),
    ) -> list[dict]:
        """
        Generate a game's recorded art plan and import each asset.

        The plan lives in `funcs/art_plan.py`; it names a subject, an asset
        type and a **height in metres**, because a mesh normalised into a
        unit box has no size of its own. Concept images come from
        `image_model` unless an entry points at one.

        Facing is recorded as `heuristic`, never as verified: single-image
        reconstruction puts the input view on a predictable axis, but a
        guess labelled as checked stops anyone checking. Each import leaves
        a review sheet for `agent_skills/asset_qa/`.
        """
        from .funcs.art_plan import concept_image, plan_for_game

        entries = plan if plan is not None else plan_for_game(game_id)
        if not entries:
            raise ValueError(
                f"No art plan for {game_id!r}; add one to "
                "operators/gen_3d_object/funcs/art_plan.py"
            )

        results: list[dict] = []
        for entry in entries:
            if assets and entry["asset_id"] not in assets:
                continue
            image, provenance, framing = concept_image(entry, image_model)
            task_dir = Path(
                self._resolve_out_path(
                    {"game_id": game_id}, entry["task_id"]
                )[1]
            )
            task_dir.mkdir(parents=True, exist_ok=True)
            # Keep the concept image beside the mesh it produced: a bad
            # asset is almost always a bad concept image, and that is not
            # diagnosable after the fact if the input was thrown away.
            image.save(task_dir / "concept.png")
            result = self.run(
                {
                    "game_id": game_id,
                    "task_id": entry["task_id"],
                    "image": image,
                    "prompt": entry["full_prompt"],
                    "seed": entry.get("seed", 42),
                    "decimation_target": entry["triangles"],
                    "texture_size": entry["texture"],
                    "asset_id": entry["asset_id"],
                    "asset_type": entry["type"],
                    "forward_axis": entry["faces"],
                    "scale_hint_metres": entry["height"],
                    "verified_by": "heuristic",
                    "notes": entry["notes"]
                    or f"Generated from: {provenance}. Facing assumed "
                    "from the input view.",
                }
            )
            result["asset_id"] = entry["asset_id"]
            result["concept_source"] = provenance
            result["framing"] = framing
            if framing.get("touched_border"):
                # The subject ran off the edge of the generated image, so
                # part of it was never drawn. Cropping cannot invent it.
                result.setdefault("warnings", []).append(
                    "the concept image was cropped at the border, so the "
                    "mesh is probably truncated: regenerate with another "
                    "seed"
                )
            results.append(result)
        return results

    # --------------------------------------------------------------------------

    def run_batch(self, inputs: list[dict]) -> list[dict]:
        """Run a list of input dicts sequentially and return results."""
        return [self.run(inp) for inp in inputs]
