"""Step functions for the 3D object operator."""

from .art_plan import (
    DEFAULT_DECIMATION_TARGET,
    DEFAULT_TEXTURE_SIZE,
    GAME_ART_PLANS,
    GENERATED_FORWARD_AXIS,
    PROMPT_STYLE,
    concept_image,
    describe_plans,
    frame_subject,
    neutral_canvas,
    plan_for_game,
)
from .code_asset import (
    AXES,
    GATES,
    KINDS,
    MAX_ATTEMPTS,
    MESH_KIND,
    PRIMITIVES,
    SpecError,
    build_code_asset,
    correct_spec,
    estimate_triangles,
    run_gates,
    spec_bounds,
    suits_code_asset,
    validate_spec,
)
from .mesh_cleanup import strip_ground_plate

__all__ = [
    "AXES",
    "DEFAULT_DECIMATION_TARGET",
    "DEFAULT_TEXTURE_SIZE",
    "GAME_ART_PLANS",
    "GATES",
    "GENERATED_FORWARD_AXIS",
    "KINDS",
    "MAX_ATTEMPTS",
    "MESH_KIND",
    "PRIMITIVES",
    "PROMPT_STYLE",
    "SpecError",
    "build_code_asset",
    "concept_image",
    "correct_spec",
    "describe_plans",
    "estimate_triangles",
    "frame_subject",
    "neutral_canvas",
    "plan_for_game",
    "run_gates",
    "spec_bounds",
    "strip_ground_plate",
    "suits_code_asset",
    "validate_spec",
]
